export const bodyTypeListItem = [
  { label: "Mảnh khảnh", value: "Slim" },
  { label: "Gầy", value: "Thin" },
  { label: "Gầy nhom", value: "Skinny" },
  { label: "Gầy lêu nghêu", value: "Lanky" },
  { label: "Nhỏ nhắn", value: "Petite" },
  { label: "Tí hon", value: "Tiny" },
  { label: "Mỏng manh", value: "Slight" },
  { label: "Cân đối", value: "Fit" },
  { label: "Thể thao", value: "Athletic" },
  { label: "Cơ bắp", value: "Muscular" },
  { label: "Vạm vỡ", value: "Buff" },
  { label: "Đô con", value: "Beefy" },
  { label: "Hình thể đẹp", value: "Well-built" },
  { label: "Đồng hồ cát", value: "Hourglass" },
  { label: "Gợi cảm", value: "Voluptuous" },
  { label: "Mũm mĩm", value: "Chubby" },
  { label: "Tròn trịa", value: "Plump" },
  { label: "Tròn vo", value: "Rotund" },
  { label: "To lớn", value: "Large" },
  { label: "Chắc nịch", value: "Stocky" },
  { label: "Bệ vệ", value: "Portly" },
  { label: "To béo", value: "Stout" },
  { label: "Nặng nề", value: "Hefty" },
];
