export const faceDetailListItem = {
  shapes: [
    { label: "Tròn", value: "Round" },
    { label: "Trái xoan", value: "Oval" },
    { label: "Vuông", value: "Square" },
    { label: "Trái tim", value: "Heart" },
    { label: "Kim cương", value: "Diamond" },
    { label: "Chữ nhật", value: "Rectangle" },
    { label: "Dài", value: "Long" },
    { label: "Tam giác ngược", value: "Inverted Triangle" },
    { label: "Cằm V-Line", value: "Heart with V-Shape Chin" },
    { label: "Gò má cao", value: "Round with High Cheekbones" },
    { label: "Góc cạnh", value: "Square with Sharp Jaw" },
  ],
  freckles: [
    { label: "Không tàn nhang", value: "No Freckles" },
    { label: "Một chút", value: "A Few Very Light Freckles" },
    { label: "Sắc nét", value: "Pronounced Freckles" },
    { label: "Dày đặc", value: "Dense Freckles" },
    { label: "Nắng hôn (Sun-kissed)", value: "Sun-kissed Freckles" },
    { label: "Trên mũi", value: "Across the Nose Freckles" },
    { label: "Trên má", value: "Cheek Freckles" },
    { label: "Khắp mặt", value: "All-over Freckles" },
    { label: "Tự nhiên", value: "Noticeable but Natural Freckles" },
  ],
  eyes: [
    { label: "Tự nhiên", value: "Natural Eye Details" },
    { label: "Chi tiết cao", value: "Highly Defined Eyes" },
    { label: "Sắc nét", value: "Sharp Eye Details" },
    { label: "Sống động", value: "Lifelike Eye Realism" },
    { label: "Lông mi chi tiết", value: "Detailed Eyelashes" },
    { label: "Có hồn", value: "Expressive Eye Details" },
    { label: "Lấp lánh", value: "Sparkling Eye Details" },
    { label: "Mắt sáng", value: "Clear and Focused Eyes" },
  ],
  iris: [
    { label: "Chi tiết mống mắt", value: "Intricate Iris Details" },
    { label: "Vòng Limbal rõ", value: "Clearly Defined Limbal Ring" },
    { label: "Màu sâu", value: "Deep Iris Coloration" },
    { label: "Vân mắt", value: "Striated Iris" },
    { label: "Đốm mắt", value: "Speckled Iris" },
    { label: "Thôi miên", value: "Hypnotic Iris Detail" },
  ],
  makeup: [
    { label: "Tự nhiên", value: "Natural Makeup" },
    { label: "Hàn Quốc (Dewy)", value: "Dewy Makeup" },
    { label: "Cổ điển", value: "Classic Makeup" },
    { label: "Quyến rũ (Glam)", value: "Glam Makeup" },
    { label: "Mắt khói", value: "Smokey Eye Makeup" },
    { label: "Nghệ thuật", value: "Artistic Makeup" },
    { label: "Retro/Vintage", value: "Vintage Makeup" },
    { label: "Không makeup", value: "No Makeup" },
  ],
  beard: [
    { label: "Râu lởm chởm", value: "Stubble Beard" },
    { label: "Râu quai nón", value: "Full Beard" },
    { label: "Râu dê", value: "Goatee" },
    { label: "Ria mép", value: "Chevron Mustache" },
    { label: "Nhẵn nhụi", value: "Clean Shaven" },
    { label: "Lịch lãm", value: "Corporate Beard" },
    { label: "Quai nón mỏng", value: "Chinstrap Beard" },
  ],
  expression: [{ label: "Nhìn vào máy ảnh", value: "Look at camera" }],
};
