export const hairDetailListItem = {
  lengths: [
    { label: "Ngắn", value: "Short" },
    { label: "Trung bình", value: "Medium" },
    { label: "Dài", value: "Long" },
    { label: "Rất dài", value: "Very Long" },
  ],
  colors: [
    { label: "Đen", value: "Black" },
    { label: "Đen nhánh", value: "Jet Black" },
    { label: "Vàng (Blonde)", value: "Blonde" },
    { label: "Bạch kim", value: "Platinum" },
    { label: "Nâu hạt dẻ", value: "Chestnut" },
    { label: "Nâu Chocolate", value: "Chocolate" },
    { label: "Đỏ", value: "Red" },
    { label: "Đỏ nâu (Auburn)", value: "Auburn" },
    { label: "Đồng (Copper)", value: "Copper" },
    { label: "Rượu vang", value: "Burgundy" },
    { label: "Xám", value: "Gray" },
    { label: "Bạc", value: "Silver" },
    { label: "Trắng", value: "White" },
    { label: "Muối tiêu", value: "Salt and pepper" },
    { label: "Hồng pastel", value: "Pastel Pink" }, // Thêm ví dụ pastel
    { label: "Nhiều màu", value: "Multicolored" },
    { label: "Highlight", value: "Balayage" }, // Balayage thường là màu/kỹ thuật
  ],
  // Phân nhóm Style để dễ tìm
  styleGroups: [
    {
      name: "Ngắn / Nam tính / Cá tính",
      items: [
        "Bald",
        "Buzz",
        "Crew",
        "Caesar",
        "Modern caesar",
        "Faded afro",
        "High skin fade",
        "Box fade",
        "Taper fade with waves",
        "Flat topcut",
        "Undercut",
        "Side Part Comb-Overstyle With High Fade",
        "Pompadour",
        "Quiff",
        "Mohawk",
        "Frohawk",
        "Faux hawk",
        "Spiky",
        "Textured brush back",
        "Tomboy",
      ],
    },
    {
      name: "Bob / Tóc lỡ",
      items: [
        "Bob",
        "Blunt bob",
        "French bob",
        "Italian bob",
        "A-line bob",
        "Stacked bob",
        "Wavy bob",
        "Curly bob",
        "Long bob",
        "Smooth lob",
        "Shag",
        "Mullet",
        "Pixie",
        "Long pixie",
        "Short curly pixie",
        "Asymmetrical",
        "Choppy",
      ],
    },
    {
      name: "Dài / Xoăn / Gợn sóng",
      items: [
        "Long straight",
        "Long with bangs",
        "Wavy",
        "Very long wave",
        "Curly",
        "Loose Curly Afro",
        "Hair ringlets",
        "Marmaid waves",
        "Beach waves",
        "Layered",
        "Feathered",
        "Straight",
      ],
    },
    {
      name: "Tết / Búi / Buộc",
      items: [
        "Ponytail",
        "High ponytail",
        "Low ponytail",
        "Pigtails",
        "Braided pigtails",
        "Twintails",
        "Bun",
        "Double Bun",
        "Space buns",
        "Top Knot",
        "Man bun",
        "Chignon",
        "Updo",
        "Ballerina bun",
        "Braided",
        "French braids",
        "Dutch braids",
        "Fishtail braids",
        "Box braids",
        "Micro braids",
        "Cornrows",
        "Dreadlocks",
        "Waterfall braids",
        "Lemonade braids",
      ],
    },
    {
      name: "Mái / Chi tiết khác",
      items: [
        "Bangs",
        "Curtain bangs",
        "Side-swept bangs",
        "Wispy bangs",
        "Blunt bangs",
        "Side Part",
        "Middle Part",
        "Deep side part",
        "Messy",
        "Disheveled",
        "Windblown",
      ],
    },
  ],
};
