export const hairDetailListItem = {
  lengths: [
    { label: "Ngắn", value: "Short" },
    { label: "Trung bình", value: "Medium" },
    { label: "Dài", value: "Long" },
    { label: "Rất dài", value: "Very Long" },
  ],
  colors: [
    { label: "Đen", value: "Black" },
    { label: "Đen nhánh", value: "Jet Black" },
    { label: "Vàng (Blonde)", value: "Blonde" },
    { label: "Bạch kim", value: "Platinum" },
    { label: "Nâu hạt dẻ", value: "Chestnut" },
    { label: "Nâu Chocolate", value: "Chocolate" },
    { label: "Đỏ", value: "Red" },
    { label: "Đỏ nâu (Auburn)", value: "Auburn" },
    { label: "Đồng (Copper)", value: "Copper" },
    { label: "Rượu vang", value: "Burgundy" },
    { label: "Xám", value: "Gray" },
    { label: "Bạc", value: "Silver" },
    { label: "Trắng", value: "White" },
    { label: "Muối tiêu", value: "Salt and pepper" },
    { label: "Hồng pastel", value: "Pastel Pink" }, // Thêm ví dụ pastel
    { label: "Nhiều màu", value: "Multicolored" },
    { label: "Highlight", value: "Balayage" }, // Balayage thường là màu/kỹ thuật
  ],
  // Phân nhóm Style để dễ tìm
  styleGroups: [
    { label: "Bob", value: "Bob" },
    { label: "Blunt Bob", value: "Blunt bob" },
    { label: "French Bob", value: "French bob" },
    { label: "Italian Bob", value: "Italian bob" },
    { label: "A-line Bob", value: "A-line bob" },
    { label: "Stacked Bob", value: "Stacked bob" },
    { label: "Wavy Bob", value: "Wavy bob" },
    { label: "Curly Bob", value: "Curly bob" },
    { label: "Long Bob", value: "Long bob" },
    { label: "Smooth Lob", value: "Smooth lob" },
    { label: "Shag", value: "Shag" },
    { label: "Mullet", value: "Mullet" },
    { label: "Pixie", value: "Pixie" },
    { label: "Long Pixie", value: "Long pixie" },
    { label: "Short Curly Pixie", value: "Short curly pixie" },
    { label: "Asymmetrical", value: "Asymmetrical" },
    { label: "Choppy", value: "Choppy" },
    { label: "Long Straight", value: "Long straight" },
    { label: "Long with Bangs", value: "Long with bangs" },
    { label: "Wavy", value: "Wavy" },
    { label: "Very Long Wave", value: "Very long wave" },
    { label: "Curly", value: "Curly" },
    { label: "Loose Curly Afro", value: "Loose Curly Afro" },
    { label: "Hair Ringlets", value: "Hair ringlets" },
    { label: "Mermaid Waves", value: "Mermaid waves" },
    { label: "Beach Waves", value: "Beach waves" },
    { label: "Layered", value: "Layered" },
    { label: "Feathered", value: "Feathered" },
    { label: "Straight", value: "Straight" },
    { label: "Ponytail", value: "Ponytail" },
    { label: "High Ponytail", value: "High ponytail" },
    { label: "Low Ponytail", value: "Low ponytail" },
    { label: "Pigtails", value: "Pigtails" },
    { label: "Braided Pigtails", value: "Braided pigtails" },
    { label: "Twintails", value: "Twintails" },
    { label: "Bun", value: "Bun" },
    { label: "Double Bun", value: "Double Bun" },
    { label: "Space Buns", value: "Space buns" },
    { label: "Top Knot", value: "Top Knot" },
    { label: "Man Bun", value: "Man bun" },
    { label: "Chignon", value: "Chignon" },
    { label: "Updo", value: "Updo" },
    { label: "Ballerina Bun", value: "Ballerina bun" },
    { label: "Braided", value: "Braided" },
    { label: "French Braids", value: "French braids" },
    { label: "Dutch Braids", value: "Dutch braids" },
    { label: "Fishtail Braids", value: "Fishtail braids" },
    { label: "Box Braids", value: "Box braids" },
    { label: "Micro Braids", value: "Micro braids" },
    { label: "Cornrows", value: "Cornrows" },
    { label: "Dreadlocks", value: "Dreadlocks" },
    { label: "Waterfall Braids", value: "Waterfall braids" },
    { label: "Lemonade Braids", value: "Lemonade braids" },
    { label: "Bangs", value: "Bangs" },
    { label: "Curtain Bangs", value: "Curtain bangs" },
    { label: "Side-swept Bangs", value: "Side-swept bangs" },
    { label: "Wispy Bangs", value: "Wispy bangs" },
    { label: "Blunt Bangs", value: "Blunt bangs" },
    { label: "Side Part", value: "Side Part" },
    { label: "Middle Part", value: "Middle Part" },
    { label: "Deep Side Part", value: "Deep side part" },
    { label: "Messy", value: "Messy" },
    { label: "Disheveled", value: "Disheveled" },
    { label: "Windblown", value: "Windblown" },
  ],
};
